name: Daily GitHub Contribution

on:
  schedule:
    # Run daily at a random time (this example is 8:30 AM UTC)
    - cron: '30 8 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  make_contribution:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for accurate streak tracking
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Make daily contributions
        run: |
          python daily_contribution.py
          
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Daily contribution update $(date +'%Y-%m-%d')"
          git push
